### PR TITLE
fix(security): keep ignored and nested-repo secrets out of turn blockers, still surfaced in audits (refs #2575)

### PR DESCRIPTION
**Pull request by stekman08**
## Summary

- keep scanning gitignored files for explicit secret audits, but demote them from blocking diagnostics
- identify findings inside nested Git repositories so parent scans do not claim submodule contents
- exclude demoted Gitleaks findings from both blocker and stale-secret automatic turn context

## Why

Pi-Lens runs Gitleaks with `--no-git --source`, then classifies findings as tracked, untracked, ignored, or scratch. The automatic turn-end path previously discarded that classification and promoted every live Gitleaks finding to a `STOP` blocker. This caused ignored local `.env` files and files belonging to submodules to be described as committed source leaks and injected into agent context.

Blanket `.gitignore` exclusion would hide credentials from explicit audits. This change keeps those findings available through project diagnostics while limiting automatic blocking context to tracked files, ordinary non-ignored untracked files, and fail-open findings whose Git status could not be established.

## Validation

- `npm run build`
- `npm run lint`
- targeted Vitest: 74 passed
- changed-file formatting check passed
- full unit suite: 12,528 passed, 59 skipped, 43 failed for unrelated environment/baseline issues on current `master` (primarily macOS `/private/var` path normalization and worktree fixture assumptions; the two changed test files pass independently)

### CODE REVIEW

**Comment by apmantza** [comment]
Verdict: merge after fixes.

The security classification itself passed the production probes. The PR is not merge-ready because the merged tree has one required hook-bound failure and one required type-check failure.

## Findings

### HIGH F1 — Unbounded await on the turn-end hook

1. `node_modules/.bin/vitest run tests/config/hook-await-bounds.test.ts --configLoader runner` reports:

   ```text
   clients/runtime-turn.ts#e75a4aef~20888363 (clients/runtime-turn.ts:1876  const classifiedGitleaksFindings = await classifyAndFilterFindings())
   An await: wrap it in bounded() from clients/deadline-utils.ts
   ```

   Expected: the new Git classification await is registered or bounded. Actual: it is neither.

2. `clients/runtime-turn.ts:1876` awaits two Git-backed status probes directly on `turn_end`.

3. A Git process can stall before its leaf timeout, so the hook can spend work outside the hook budget and delay turn completion. The required AC1 governance test is red on the exact merged tree.

4. Wrap the classification in `bounded()` using the turn-end budget and `ctx.signal`, or move the work behind an already bounded helper. Register the resulting call only when the bound is real.

### HIGH F2 — The new test does not type-check

1. `PI_LENS_HOME="$PWD/.probe-home" npm run lint` reports:

   ```text
   tests/clients/gitleaks-scratch-exclusion.test.ts(278,29): error TS2322:
   Type '"ignored" | "nested-repository"' is not assignable to type
   '"ignored" | "scratch" | "tracked" | "untracked" | undefined'.
   ```

   Expected: the new diagnostic test compiles. Actual: its `finding()` helper type rejects the new `nested-repository` value.

2. The test adds `nested-repository` to the production union but leaves the test helper's `pathStatus` union unchanged.

3. The required `Lint & type-check` gate cannot pass, even though Vitest transpilation runs the test body.

4. Add `nested-repository` to the helper's type, or type the helper from `GitleaksFinding["pathStatus"]` so future status additions cannot drift from the test fixture.

## Security probes

On a real temporary parent repository with a tracked file, an ignored file, an ordinary untracked file, and a nested repository, the production classifier and adapter returned:

```text
tracked.txt       tracked             blocking
ignored.env       ignored             none
untracked.txt     untracked           blocking
nested/secret.txt nested-repository   none
```

Adding `tracked.txt` to `.gitignore` afterward still returned `tracked`. A directory outside Git returned no `pathStatus` and remained `blocking`, which confirms fail-open means block. A `.git` file boundary was detected; `foo.git/secret.txt` remained `untracked`, with no false demotion.

The real turn-end seam tests pass for the tracked/untracked blocker path and the ignored/nested/scratch context suppression. The explicit `lens_diagnostics` audit test passes on the merged tree, and the adapter retains `[git: ignored]` or `[git: nested-repository]` in the diagnostic message.

The Windows-shaped allowlist probe passes. The classifier uses the host `path` implementation and receives Gitleaks' native separators; a POSIX process must not be used as evidence for Windows filesystem resolution.

## Verification

- Build: passed.
- Changed tests plus `tests/config`: 211 passed, 1 failed. The only failure is F1.
- Red-first: after restoring the four production files to `origin/master` and rebuilding, the changed suite failed 3 tests, including the new nested-repository and ignored-demotion expectations.
- Mutation: changing the classifier to return `tracked` for every finding failed 6 tests. The ignored `.env` assertion changed from expected `ignored` to received `tracked`.
- Preflight: build, formatting, changelog checks, config tests, generation guard, ratchets, coverage, and CI verdict passed; lint failed with F2.
- No changelog fragment was added, as requested. The PR still needs its required fragment before merge.

## Could not verify

- The `gitleaks` executable is not installed in this environment, so I did not run a real binary scan. The classifier, turn-end cache path, adapter, and diagnostics renderer were exercised through the repository's production seams.
- Under the default harness Git guard, five temporary-repository tests were blocked because `git init` outside this worktree was refused. I reran those isolated tests with `/usr/bin/git`, a worktree-local probe home, and no source changes.
- I did not inspect a Windows runtime; the path-shape checks were limited to `path.win32`-shaped inputs and the existing separator-regex test.

## Named output

- Worth exploring: turn-end classification now performs Git-backed status work in the hook path. The existing 30-second cache in `git-tracked-ignore.ts` bounds repeated spawns, but the first classification still needs the hook-level `bounded()` contract required by F1.

Cleared categories: tracked-vs-ignored precedence, fail-open blocking, nested `.git` file/directory detection, `foo.git` false positives, audit visibility, stale-secret suppression, mutation sensitivity, and bounded per-finding status observability.

**Comment by apmantza** [comment]
## Maintainer round

Operating rule: turn-end Gitleaks classification is bounded by the hook budget and timeout retains raw findings so security delivery fails open.

Kept: contributor production behavior, tests, and diagnostic classification remain unchanged except for the requested timeout bound and type-source correction.

### Findings

- F1 HIGH — fixed. `classifyAndFilterFindings()` now uses `bounded()` with `HOOK_WALL_BUDGET_MS.turn_end`, `deps.signal`, and a registered provenance entry. Timeout retains the raw findings and records `gitleaks_classification_timeout` once per session.
- F2 HIGH — fixed. `pathStatus` callback parameters use `GitleaksFinding["pathStatus"]` so test unions follow production.

### Red-first evidence

- Hook sweep before the fix: `1 flagged item(s) ... clients/runtime-turn.ts:1876 ... await classifyAndFilterFindings()`.
- Lint red quoted by review r1: `TS2322: Type '"ignored" | "nested-repository"' is not assignable to type '"ignored" | "scratch" | "tracked" | "untracked" | undefined'.`
- Mutation removing `bounded()`: 13 tests, 2 failed. The sweep reported the unregistered bounded call and the unbounded classification await.

### Tests

- `tests/clients/gitleaks-scratch-exclusion.test.ts`: 23 passed.
- `tests/clients/gitleaks-client.test.ts`: 26 passed.
- `tests/clients/runtime-turn-session.test.ts`, `tests/tools/lens-diagnostics.test.ts`, and `tests/config/`: 44 files, 561 passed.
- `tests/config/hook-await-bounds.test.ts`: 13 passed after restoration.
- `npm run lint`: passed.

The first Gitleaks run was blocked by the worker Git guard refusing temporary `git init` calls. Re-running with `PATH=/usr/bin:/bin` passed the real-fixture tests.

### Blast radius

The changed production path is `index.ts` → `handleTurnEnd()` → `bounded()` → `classifyAndFilterFindings()`, followed by the existing Gitleaks diagnostic adapter and freshness gates. The only new host input is the existing `ctx.signal`, threaded through `TurnEndDeps`; the MCP adapter and unit harnesses remain optional-signal callers.

### Class sweep

The hook-await scan, bounded-call provenance registry, and helper-await population pin were updated for the new shared call. No other direct Gitleaks classification call sites exist.

### Observability

`bounded()` emits its standard bounded-await record. A timeout additionally emits `gitleaks_classification_timeout` through `recordDegradationOnce`, keyed by the working directory and reset with the session ledger. Raw findings remain blockers on timeout.

### Test assessment

The existing contributor tests remain in place. The maintainer round adds no new product test file; the hook governance test and its mutation proof cover the new bound.

### Preflight

`npm run preflight` is run last and its table will be appended below before handoff.

| gate | mirrored CI job | pass/fail | first red line |
| --- | --- | --- | --- |
| build | Lint & type-check | pass | |
| lint | Lint & type-check | pass | |
| fmt:check | oxfmt format check (advisory) | pass | |
| changelog:check | Unit tests | pass | |
| check-changelog-fragments | Changelog fragment (fast-fail) | pass | |
| check:lockfile | Lint & type-check | pass | |
| tests/config | Unit tests | pass | |
| generation-guard | Unit tests | pass | |
| flake-shape-ratchet | Unit tests | pass | |
| lsp-spawn-heavy-coverage | Unit tests | pass | |
| ci-verdict | Unit tests | pass | |
| check-pr-title | PR title | pass | |
| check-close-keywords | Close-keyword syntax | pass | |
| check-pr-body | PR body (advisory) | pass | |

**Comment by apmantza** [comment]
Merged as 66c20e59 — thank you for the contribution and for keeping the audit path intact while demoting ignored and nested-repo findings from blockers. The maintainer round only bounded the turn-end classification (fail-open on timeout) and typed the test helper from the production union.
